Update Sarama dependency
Some cantabular services have updated reported dependency conflicts when
attempting to run their unit tests, because the dp-kafka Sarama
dependency was still on `v1.30.1`.

```
mock/sarama_async_producer.go:14:40: cannot use &SaramaAsyncProducerMock{} (value of type *SaramaAsyncProducerMock) as type sarama.AsyncProducer in variable declaration:
	*SaramaAsyncProducerMock does not implement sarama.AsyncProducer (missing AbortTxn method)
```

All it was required, was to regenerate the mock
`SaramaAsyncProducerMock`